import { mount } from "dashboard/DashboardApp";
import React, { useRef, useEffect } from "react";

export default () => {
  // a referrence to an HTML element generated by React
  const reference = useRef(null);

  useEffect(() => {
    mount(reference.current);
  }, []); // only run the 'useEffect' function once, when the 'DashboardApp' component is rendered

  return <div ref={reference} />;
};
