import { mount } from "marketing/MarketingApp";
import React, { useRef, useEffect } from "react";

export default () => {
  // a referrence to an HTML element generated by React
  const reference = useRef(null);

  useEffect(() => {
    mount(reference.current);
  });
  return <div ref={reference} />;
};
